# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0020_auto_20150821_1707'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='UserQAProfile',
        ),
    ]
