# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import django_markdown.models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0023_auto_20160317_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='user_data',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_data',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='user_data',
            new_name='user',
        ),
        migrations.AddField(
            model_name='question',
            name='description',
            field=django_markdown.models.MarkdownField(default='OPt text'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=django_markdown.models.MarkdownField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
