# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 16:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0023_auto_20160317_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='user_data',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_data',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='user_data',
            new_name='user',
        ),
    ]
