# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 17:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0024_auto_20160317_1738'),
        ('qa', '0024_auto_20160317_1643'),
    ]

    operations = [
    ]
